variables:
  ml-ws-connection: 'aml-demo-connection' # Workspace Service Connection name
  ml-ws: 'aml-demo' # AML Workspace name
  ml-rg: 'aml-demo' # AML resource Group name
  ml-ct: 'cpu-cluster' # AML Compute cluster name
  ml-path: 'models/diabetes' # Model directory path in repo
  ml-exp: 'exp-test' # Experiment name
  ml-model-name: 'diabetes-model' # Model name
  ml-aks-name: 'aks-prod' # AKS cluster name

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  displayName: 'Install AML CLI (v2)'
  inputs:
    azureSubscription: $(ml-ws-connection)
    scriptLocation: inlineScript
    scriptType: 'bash'
    inlineScript: 'az extension add -n ml -y'
    
- task: AzureCLI@2
  displayName: 'Create and list compute'
  inputs:
    azureSubscription: $(ml-ws-connection)
    workingDirectory: $(ml-path)
    scriptLocation: inlineScript
    scriptType: 'bash'
    inlineScript: |
      az ml compute create --name $(ml-ct) --size Standard_NC6 --min-instances 0 --max-instances 1 --type AmlCompute --resource-group $(ml-rg) --workspace-name $(ml-ws)
      az ml compute list -w $(ml-ws) -g $(ml-rg)

- task: AzureCLI@2
  displayName: 'Train model'
  inputs:
    azureSubscription: $(ml-ws-connection)
    workingDirectory: $(ml-path)
    scriptLocation: inlineScript
    scriptType: 'bash'
    inlineScript: |
      az ml job create -f job.yml -w $(ml-ws) -g $(ml-rg) --stream
      az ml job download -n 865598c2-72f0-4653-82ed-13cc3c8a46bd --outputs -w $(ml-ws) -g $(ml-rg) 
     
# Somehow get runid from az ml job create

- task: AzureCLI@2
  displayName: 'Delete compute'
  inputs:
    azureSubscription: $(ml-ws-connection)
    workingDirectory: $(ml-path)
    scriptLocation: inlineScript
    scriptType: 'bash'
    inlineScript: 'az ml compute delete -n $(ml-ct) -w $(ml-ws) -g $(ml-rg) -y'

# Add potential approval step before registration of model

- task: AzureCLI@2
  displayName: 'Deploy endpoint (Register model etc.)'
  inputs:
    azureSubscription: $(ml-ws-connection)
    workingDirectory: $(ml-path)
    scriptLocation: inlineScript
    scriptType: 'bash'
    inlineScript: |
      az ml endpoint create -f endpoint.yml -w $(ml-ws) -g $(ml-rg)
      az ml endpoint list -w $(ml-ws) -g $(ml-rg)

- task: AzureCLI@2
  displayName: 'Delete endpoint'
  inputs:
    azureSubscription: $(ml-ws-connection)
    workingDirectory: $(ml-path)
    scriptLocation: inlineScript
    scriptType: 'bash'
    inlineScript: 'az ml endpoint delete -n aml-demo9000-endpoint -w $(ml-ws) -g $(ml-rg) -y'

# Add potential automated tests
